"""
Module de peuplement initial (Seed) pour le patrimoine culturel CultureLens dans alta_db.
Enregistre en base de données l'intégralité des monuments (avec priorité absolue sur Bamako),
des personnages historiques, des villes/terroirs, des contes, des proverbes et des packs hors ligne.
"""

from datetime import datetime
import json
import logging
from sqlalchemy.orm import Session

from backend.src.db.models import (
    CultureMonument,
    CulturePersonnage,
    CultureLieu,
    CultureConte,
    CultureProverbe,
    CulturePack,
)

logger = logging.getLogger("AlternIA.CultureSeed")


# ==============================================================================
# 1. MONUMENTS ET SITES HISTORIQUES (PRIORITÉ BAMAKO + TOUT LE MALI)
# ==============================================================================

MONUMENTS_DATA = [
    # ── A. MONUMENTS DE BAMAKO (PRIORITAIRES) ──────────────────────────────────
    {
        "id": "monument_independance_bamako",
        "nom": "Monument de l'Indépendance",
        "sous_titre": "Symbole éternel de la souveraineté nationale et du panafricanisme",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Inauguré dans les années 1990 • Hommage au 22 septembre 1960",
        "style_architectural": "Obélisque monumentaliste moderne orné de bas-reliefs patriotiques et flèche céleste",
        "details_localisation": "Boulevard de l'Indépendance, Hamdallaye / Centre administratif",
        "photo_url": "assets/images/culture/personnages/soundiata.jpg",
        "tag": "Monument National Emblématique",
        "latitude": 12.6392,
        "longitude": -8.0029,
        "badge_debloque": "Pionnier de la Souveraineté",
        "xp_recompense": 60,
        "mots_cles": ["independance", "obelisque", "bamako", "modibo", "keita", "1960", "souverainete", "patrie", "boulevard"],
        "caracteristiques_detection": [
            {"label": "Obélisque vertical élancé (25m)", "confidence": 0.992, "category": "Structure", "icon": "trending_up_rounded"},
            {"label": "Bas-reliefs en bronze figurant les pères de la nation", "confidence": 0.985, "category": "Détail", "icon": "military_tech_rounded"},
            {"label": "Socle pyramidal en marbre et granit", "confidence": 0.978, "category": "Matériau", "icon": "layers_rounded"},
            {"label": "Axe du Boulevard de l'Indépendance", "confidence": 0.970, "category": "Topographie", "icon": "place_rounded"},
        ],
        "secrets_et_mysteres": "Le monument abrite une crypte commémorative scellée et le socle de la flamme du souvenir. Chaque 22 septembre, les délégations de toute l'Afrique y déposent des couronnes de la concorde.",
        "recit_historique": "Érigé pour immortaliser l'accession de la République du Mali à l'indépendance le 22 septembre 1960, le monument célèbre la vision de Modibo Keïta et des artisans de la liberté. Il incarne le non catégorique à la sujétion et le ralliement indéfectible à l'Union des peuples africains.",
        "narration_audio_texte": "Vous contemplez le Monument de l'Indépendance du Mali, qui s'élève fièrement sur le grand boulevard de Bamako. Cet obélisque géant rappelle à chaque génération le courage des pères fondateurs de 1960 et le serment inaltérable de la liberté nationale.",
        "pourquoi_ce_lieu_compte": "C'est le repère patriotique central de la nation malienne et le lieu cérémoniel d'affirmation de la souveraineté.",
        "route_path": "/culture/monument/monument_independance_bamako",
        "modele_3d_url": "assets/models/monument_independance.glb",
        "ar_disponible": True,
        "statut_validation": "Validé Archives Nationales",
    },
    {
        "id": "monument_tour_afrique_bamako",
        "nom": "La Tour de l'Afrique",
        "sous_titre": "Le Phare du Panafricanisme et de la Fraternité Sahélienne",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Inaugurée en 2001 lors du Sommet France-Afrique",
        "style_architectural": "Tour néo-sahélienne de 46 mètres évoquant un baobab sacré surmonté d'une corbeille de l'union",
        "details_localisation": "Rond-point de Faladié, Carrefour de la Paix, Commune VI",
        "photo_url": "assets/images/culture/villes/djenne_ville.jpg",
        "tag": "Symbole de l'Unité Africaine",
        "latitude": 12.5935,
        "longitude": -7.9463,
        "badge_debloque": "Bâtisseur de l'Unité Africaine",
        "xp_recompense": 60,
        "mots_cles": ["tour", "afrique", "faladie", "baobab", "corbeille", "panafricanisme", "bamako", "aeroport"],
        "caracteristiques_detection": [
            {"label": "Silhouette évasée en forme de baobab (46m)", "confidence": 0.994, "category": "Structure", "icon": "nature_rounded"},
            {"label": "Corbeille supérieure de la concorde", "confidence": 0.988, "category": "Symbole", "icon": "all_inclusive_rounded"},
            {"label": "Enduit ocre et fresques céramiques des 54 pays", "confidence": 0.976, "category": "Détail", "icon": "public_rounded"},
        ],
        "secrets_et_mysteres": "La corbeille au sommet symbolise le mythe de la jarre percée : nul ne peut étancher la soif d'un continent seul, mais unis, les doigts des peuples retiennent l'eau de la paix et de la prospérité.",
        "recit_historique": "Construite au carrefour stratégique menant à l'aéroport et aux régions du sud, la Tour de l'Afrique est un vibrant hommage à l'idéal des États-Unis d'Afrique et à la solidarité interétatique.",
        "narration_audio_texte": "Dressée à 46 mètres au-dessus du rond-point de Faladié, la Tour de l'Afrique accueille les visiteurs entrant à Bamako. Ses lignes sinueuses rendent hommage à l'arbre à palabres et rappellent la vocation du Mali à être le carrefour éternel de l'unité africaine.",
        "pourquoi_ce_lieu_compte": "C'est l'un des monuments les plus hauts et les plus photographiés d'Afrique de l'Ouest.",
        "route_path": "/culture/monument/monument_tour_afrique_bamako",
        "modele_3d_url": "assets/models/tour_afrique.glb",
        "ar_disponible": True,
        "statut_validation": "Validé Ministère de la Culture",
    },
    {
        "id": "monument_paix_bamako",
        "nom": "Le Monument de la Paix",
        "sous_titre": "La Colombe de la Concorde et de la Réconciliation",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Érigé en 1996 • Dans la ferveur de la Flamme de la Paix",
        "style_architectural": "Colombe blanche monumentale aux ailes déployées au-dessus du globe terrestre",
        "details_localisation": "Rond-point de la Paix, Hamdallaye ACI 2000, Commune IV",
        "photo_url": "assets/images/culture/contes/savane_crepuscule_stage.jpg",
        "tag": "Monument National de Concorde",
        "latitude": 12.6322,
        "longitude": -8.0261,
        "badge_debloque": "Artisan de la Paix",
        "xp_recompense": 50,
        "mots_cles": ["paix", "colombe", "aci 2000", "hamdallaye", "reconciliation", "concorde", "bamako"],
        "caracteristiques_detection": [
            {"label": "Colombe sculpturale blanche en envol", "confidence": 0.990, "category": "Symbole", "icon": "flutter_dash_rounded"},
            {"label": "Sphère terrestre en acier ajouré", "confidence": 0.982, "category": "Structure", "icon": "public_rounded"},
            {"label": "Bassin d'eau circulaire réfléchissant", "confidence": 0.970, "category": "Environnement", "icon": "water_rounded"},
        ],
        "secrets_et_mysteres": "Le monument a été érigé suite à l'accord historique de Tombouctou en 1996 où plus de 3 000 fusils de guerre furent brûlés dans un brasier d'espoir.",
        "recit_historique": "Situé dans le quartier d'affaires d'ACI 2000, le monument rappelle que la paix n'est pas un vain mot, mais un comportement quotidien inscrit dans la parenté à plaisanterie (Sinankunya).",
        "narration_audio_texte": "Vous admirez le Monument de la Paix d'Hamdallaye ACI 2000. La colombe immaculée prenant son essor symbolise le triomphe du dialogue sur la discorde.",
        "pourquoi_ce_lieu_compte": "Rappel solennel de la réconciliation et du vivre-ensemble entre toutes les communautés maliennes.",
        "route_path": "/culture/monument/monument_paix_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé",
    },
    {
        "id": "monument_armee_noire_bamako",
        "nom": "Monument des Héros de l'Armée Noire",
        "sous_titre": "Hommage universel aux Tirailleurs et Combattants Africains",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Conçu en 1924 • Réhabilité solennellement en 2004",
        "style_architectural": "Statuaire monumentale en bronze représentant des soldats africains solidaires",
        "details_localisation": "Place de la Liberté, Centre-ville, Commune III",
        "photo_url": "assets/images/culture/personnages/soundiata.jpg",
        "tag": "Mémoire Militaire & Universelle",
        "latitude": 12.6514,
        "longitude": -7.9982,
        "badge_debloque": "Mémoire des Tirailleurs",
        "xp_recompense": 55,
        "mots_cles": ["tirailleurs", "armee noire", "liberte", "guerre", "heros", "bamako", "bronze", "place"],
        "caracteristiques_detection": [
            {"label": "Groupe sculpté de soldats africains en uniforme d'époque", "confidence": 0.991, "category": "Sculpture", "icon": "groups_rounded"},
            {"label": "Piédestal en pierre de taille rouge", "confidence": 0.980, "category": "Matériau", "icon": "foundation_rounded"},
            {"label": "Emplacement central sur la Place de la Liberté", "confidence": 0.974, "category": "Topographie", "icon": "location_city_rounded"},
        ],
        "secrets_et_mysteres": "Ce monument est la réplique exacte de celui érigé à Reims en France en 1924, détruit durant l'occupation de 1940, puis reconstruit grâce aux archives conservées à Bamako.",
        "recit_historique": "Ce mémorial consacre le sacrifice suprême consenti par les fils du Mali et d'Afrique de l'Ouest pour la liberté mondiale lors des deux guerres mondiales.",
        "narration_audio_texte": "Ici s'élève le Monument des Héros de l'Armée Noire, sur la Place de la Liberté. Il honore la mémoire impérissable des tirailleurs qui ont combattu sur les champs de bataille avec un héroïsme légendaire.",
        "pourquoi_ce_lieu_compte": "Plaque tournante de la mémoire combattante africaine et de la reconnaissance internationale.",
        "route_path": "/culture/monument/monument_armee_noire_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé Archives Militaires",
    },
    {
        "id": "monument_ciwara_senou_bamako",
        "nom": "Monument de l'Hospitalité (Masque Ciwara)",
        "sous_titre": "L'incarnation sacrée du labeur agricole et de l'accueil fraternel",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Années 2000",
        "style_architectural": "Reproduction monumentale en métal ajouré du masque antilope-cheval Ciwara",
        "details_localisation": "Carrefour de l'Aéroport International Modibo Keïta, Sénou",
        "photo_url": "assets/images/culture/villes/djenne_ville.jpg",
        "tag": "Tradition et Bienvenue",
        "latitude": 12.5517,
        "longitude": -7.9548,
        "badge_debloque": "Gardien du Ciwara",
        "xp_recompense": 50,
        "mots_cles": ["ciwara", "tchiwara", "senou", "aeroport", "hospitalite", "agriculture", "bamako", "masque"],
        "caracteristiques_detection": [
            {"label": "Silhouette stylisée de l'antilope Ciwara", "confidence": 0.995, "category": "Sculpture", "icon": "pets_rounded"},
            {"label": "Cornes élancées et crinière ajourée en zigzag", "confidence": 0.989, "category": "Détail", "icon": "auto_awesome_rounded"},
            {"label": "Position de garde à la porte aéroportuaire", "confidence": 0.980, "category": "Topographie", "icon": "flight_takeoff_rounded"},
        ],
        "secrets_et_mysteres": "Dans la spiritualité bamanan, le Ciwara est l'être mythique envoyé par le Créateur pour percer le sol et apprendre la culture du mil aux humains sans jamais se décourager.",
        "recit_historique": "Placé au seuil de la capitale, le Ciwara souhaite la bienvenue aux voyageurs en leur rappelant les vertus fondamentales du peuple malien : dignité, travail de la terre et sens sacré de l'accueil.",
        "narration_audio_texte": "Dès votre arrivée à Bamako depuis l'aéroport de Sénou, le majestueux masque Ciwara vous salue. Cette silhouette d'antilope sculptée rend hommage aux maîtres cultivateurs et à la générosité légendaire du peuple malien.",
        "pourquoi_ce_lieu_compte": "C'est l'un des emblèmes culturels et artistiques les plus célèbres du Mali à travers le monde.",
        "route_path": "/culture/monument/monument_ciwara_senou_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé",
    },
    {
        "id": "monument_samory_toure_bamako",
        "nom": "Monument de l'Almamy Samory Touré",
        "sous_titre": "Le Bâtisseur de l'Empire Ouassoulou et Grand Stratège",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Érigé sous la IIIe République",
        "style_architectural": "Statue équestre impériale en bronze sur socle monolithique",
        "details_localisation": "Boulevard du 22 Octobre, Hamdallaye ACI 2000, Bamako",
        "photo_url": "assets/images/culture/personnages/soundiata.jpg",
        "tag": "Monument Historique de Résistance",
        "latitude": 12.6348,
        "longitude": -8.0315,
        "badge_debloque": "Cavalier du Ouassoulou",
        "xp_recompense": 55,
        "mots_cles": ["samory", "toure", "almamy", "cavalier", "cheval", "ouassoulou", "resistance", "aci 2000", "bamako"],
        "caracteristiques_detection": [
            {"label": "Statue équestre en bronze (cheval cabré)", "confidence": 0.993, "category": "Sculpture", "icon": "sports_score_rounded"},
            {"label": "Almamy en tenue guerrière et sabre au côté", "confidence": 0.986, "category": "Détail", "icon": "shield_rounded"},
            {"label": "Implantation sur le rond-point d'ACI 2000", "confidence": 0.975, "category": "Topographie", "icon": "place_rounded"},
        ],
        "secrets_et_mysteres": "Samory Touré avait organisé une armée moderne de 30 000 sofa et développé des forges artisanales capables de fabriquer des répliques fidèles des fusils à tir rapide Chassepot et Kropatschek.",
        "recit_historique": "L'Almamy Samory Touré (1830-1900) résista pendant près de vingt ans aux armées coloniales avec une intelligence tactique qui suscita le respect des généraux de son siècle.",
        "narration_audio_texte": "Vous voici devant la statue équestre de l'Almamy Samory Touré. Fondateur de l'Empire du Ouassoulou, il est l'une des figures militaires les plus remarquables de l'histoire africaine.",
        "pourquoi_ce_lieu_compte": "Symbole de la résistance acharnée et de la capacité industrielle précoloniale.",
        "route_path": "/culture/monument/monument_samory_toure_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé",
    },
    {
        "id": "monument_martyrs_bamako",
        "nom": "Monument des Martyrs de la Démocratie",
        "sous_titre": "L'hommage éternel aux victimes du 26 Mars 1991",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Inauguré dans les années 1990",
        "style_architectural": "Arche stylisée et sculpture d'une mère tenant son enfant vers l'horizon",
        "details_localisation": "Tête du Pont des Martyrs, Badalabougou / Fleuve Niger",
        "photo_url": "assets/images/culture/contes/savane_crepuscule_stage.jpg",
        "tag": "Mémoire Démocratique",
        "latitude": 12.6289,
        "longitude": -7.9942,
        "badge_debloque": "Gardien de la Démocratie",
        "xp_recompense": 50,
        "mots_cles": ["martyrs", "26 mars 1991", "pont des martyrs", "badalabougou", "democratie", "bamako", "fleuve"],
        "caracteristiques_detection": [
            {"label": "Arche sculptée en béton blanc et bronze", "confidence": 0.988, "category": "Structure", "icon": "architecture_rounded"},
            {"label": "Figure féminine protectrice tournée vers le ciel", "confidence": 0.982, "category": "Sculpture", "icon": "family_restroom_rounded"},
            {"label": "Entrée sud du Pont des Martyrs sur le Djoliba", "confidence": 0.978, "category": "Topographie", "icon": "bridge_rounded"},
        ],
        "secrets_et_mysteres": "C'est au pied de ce pont que la foule des manifestants de mars 1991 franchit pacifiquement le fleuve pour réclamer la fin du régime dictatorial et l'installation de la démocratie plurielle.",
        "recit_historique": "Le monument consacre le sacrifice des jeunes scolaires, des femmes et des démocrates maliens dont la bravoure a permis la rédaction de la Constitution de 1992.",
        "narration_audio_texte": "Le Monument des Martyrs, érigé au bord du fleuve Niger à la tête du pont historique, rappelle le prix payé par le peuple de Bamako pour la conquête de la liberté et du pluralisme démocratique.",
        "pourquoi_ce_lieu_compte": "Cœur de la mémoire citoyenne contemporaine du Mali.",
        "route_path": "/culture/monument/monument_martyrs_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé",
    },
    {
        "id": "monument_musee_national_bamako",
        "nom": "Musée National du Mali",
        "sous_titre": "Le Trésor Millénaire des Civilisations Sahéliennes",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Créé en 1953 • Complexe rénové en 2003 (Prix Aga Khan)",
        "style_architectural": "Architecture bioclimatique contemporaine en pierre de grès rouge locale et banco stabilisé",
        "details_localisation": "Avenue de la Liberté, au pied de Koulouba, Commune III",
        "photo_url": "assets/images/culture/monuments/mosquee_djenne.jpg",
        "tag": "Patrimoine National & Musée Universel",
        "latitude": 12.6597,
        "longitude": -7.9989,
        "badge_debloque": "Conservateur du Trésor Malien",
        "xp_recompense": 65,
        "mots_cles": ["musee", "national", "koulouba", "aga khan", "masques", "tissus", "archeologie", "bamako"],
        "caracteristiques_detection": [
            {"label": "Façades en pierres de taille de grès rouge ocre", "confidence": 0.994, "category": "Matériau", "icon": "foundation_rounded"},
            {"label": "Claustras traditionnels et toitures bioclimatiques", "confidence": 0.985, "category": "Architecture", "icon": "wb_shade_rounded"},
            {"label": "Parc verdoyant au pied de la falaise de Koulouba", "confidence": 0.978, "category": "Environnement", "icon": "park_rounded"},
        ],
        "secrets_et_mysteres": "Le musée conserve les plus anciens textiles archéologiques subsahariens découverts dans les grottes Tellem des falaises de Bandiagara, datant du XIe siècle.",
        "recit_historique": "Lauréat du prestigieux Prix Aga Khan d'Architecture en 2004, le Musée National est une institution de référence mondiale pour la préservation des arts rituels, des masques et de l'archéologie ouest-africaine.",
        "narration_audio_texte": "Vous voici au Musée National du Mali, un chef-d'œuvre architectural niché dans le Parc de Bamako. Ses galeries abritent des merveilles millénaires : poteries de Djenné-Djeno, masques dogons et étoffes sacrées.",
        "pourquoi_ce_lieu_compte": "Le plus grand sanctuaire de conservation du patrimoine matériel malien.",
        "route_path": "/culture/monument/monument_musee_national_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé Scientifique",
    },
    {
        "id": "monument_palais_culture_bamako",
        "nom": "Palais de la Culture Amadou Hampâté Bâ",
        "sous_titre": "L'Agora des Arts Vivants et de la Parole Sahélienne",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Inauguré en 1976 • Dédié à Amadou Hampâté Bâ en 1991",
        "style_architectural": "Grand amphithéâtre et salles de spectacles modernes en bordure du Djoliba",
        "details_localisation": "Badalabougou, Rive droite du fleuve Niger, Commune V",
        "photo_url": "assets/images/culture/villes/segou_koro.jpg",
        "tag": "Sanctuaire des Arts Vivants",
        "latitude": 12.6262,
        "longitude": -7.9897,
        "badge_debloque": "Maître de la Parole",
        "xp_recompense": 50,
        "mots_cles": ["palais", "culture", "amadou", "hampate ba", "theatre", "musique", "badalabougou", "bamako", "fleuve"],
        "caracteristiques_detection": [
            {"label": "Amphithéâtre semi-circulaire ouvert sur le fleuve", "confidence": 0.987, "category": "Structure", "icon": "theater_comedy_rounded"},
            {"label": "Grande esplanade bordée de rôniers et flamboyants", "confidence": 0.979, "category": "Environnement", "icon": "park_rounded"},
            {"label": "Pignon monumental aux motifs géométriques soudanais", "confidence": 0.972, "category": "Architecture", "icon": "palette_rounded"},
        ],
        "secrets_et_mysteres": "C'est dans ce temple de la culture que se réunissent les plus grands maîtres de la kora, du balafon et de la parole griotique lors des biennales artistiques et culturelles nationales.",
        "recit_historique": "Nommé en hommage à l'illustre sage et écrivain Amadou Hampâté Bâ, ce complexe incarne la vitalité créatrice, le théâtre et les musiques du Mali contemporain.",
        "narration_audio_texte": "Le Palais de la Culture Amadou Hampâté Bâ se déploie majestueusement sur les rives du fleuve Niger. Il porte le nom du sage qui nous a légué ce trésor : 'En Afrique, un vieillard qui meurt est une bibliothèque qui brûle'.",
        "pourquoi_ce_lieu_compte": "Le cœur névralgique de la création musicale, théâtrale et chorégraphique malienne.",
        "route_path": "/culture/monument/monument_palais_culture_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé",
    },
    {
        "id": "monument_kwame_nkrumah_bamako",
        "nom": "Monument Kwamé Nkrumah",
        "sous_titre": "L'Hommage au Père de l'Union Africaine",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Années 2000",
        "style_architectural": "Stèle commémorative ornée du buste en bronze de Kwamé Nkrumah",
        "details_localisation": "Rond-point Kwamé Nkrumah, Hamdallaye, Commune IV",
        "photo_url": "assets/images/culture/personnages/soundiata.jpg",
        "tag": "Mémoire Panafricaine",
        "latitude": 12.6375,
        "longitude": -8.0185,
        "badge_debloque": "Apôtre du Panafricanisme",
        "xp_recompense": 45,
        "mots_cles": ["kwame", "nkrumah", "ghana", "union africaine", "hamdallaye", "bamako", "panafricanisme"],
        "caracteristiques_detection": [
            {"label": "Buste en bronze de Kwamé Nkrumah", "confidence": 0.990, "category": "Sculpture", "icon": "person_rounded"},
            {"label": "Stèle trapézoïdale gravée de la charte de l'Union", "confidence": 0.981, "category": "Détail", "icon": "article_rounded"},
        ],
        "secrets_et_mysteres": "Ce carrefour rappelle l'Union historique Ghana-Guinée-Mali scellée en 1961 par Modibo Keïta, Kwamé Nkrumah et Sékou Touré, première esquisse de l'Organisation de l'Unité Africaine.",
        "recit_historique": "Nkrumah déclara en 1957 que l'indépendance de son pays n'avait aucun sens sans la libération totale du continent africain tout entier.",
        "narration_audio_texte": "Le Monument Kwamé Nkrumah à Bamako honore l'un des plus illustres théoriciens de la liberté africaine. Il rappelle les liens fraternels indissolubles unissant le Mali et le Ghana.",
        "pourquoi_ce_lieu_compte": "Symbole de l'amitié entre les peuples et de la fraternité historique.",
        "route_path": "/culture/monument/monument_kwame_nkrumah_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé",
    },
    {
        "id": "monument_cathedrale_bamako",
        "nom": "Cathédrale du Sacré-Cœur de Bamako",
        "sous_titre": "Joyau de Grès Rouge et Témoin de la Fraternité Interreligieuse",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Construite entre 1925 et 1936",
        "style_architectural": "Architecture néo-byzantine en briques de grès rouge taillées avec voûtes élancées",
        "details_localisation": "Centre-ville, Boulevard du Peuple, Commune III",
        "photo_url": "assets/images/culture/monuments/fort_medine.jpg",
        "tag": "Monument Historique Religieux",
        "latitude": 12.6465,
        "longitude": -7.9948,
        "badge_debloque": "Pèlerin de la Fraternité",
        "xp_recompense": 50,
        "mots_cles": ["cathedrale", "sacre coeur", "eglise", "gres rouge", "centre ville", "bamako", "chretienne"],
        "caracteristiques_detection": [
            {"label": "Façade néo-byzantine en grès rouge poli", "confidence": 0.992, "category": "Matériau", "icon": "domain_rounded"},
            {"label": "Clocher carré surmonté d'une croix lumineuse", "confidence": 0.986, "category": "Structure", "icon": "notifications_rounded"},
            {"label": "Vitraux représentant les paysages du Niger", "confidence": 0.975, "category": "Détail", "icon": "window_rounded"},
        ],
        "secrets_et_mysteres": "La première pierre fut bénie en 1925 en présence des notables musulmans de Bamako, marquant le début d'une tradition de convivialité et de respect mutuel exemplaire au Mali.",
        "recit_historique": "Siège de l'archevêché de Bamako, la cathédrale est un monument central du cœur historique de la capitale.",
        "narration_audio_texte": "La Cathédrale du Sacré-Cœur de Bamako s'élève au cœur du centre animé. Bâtie en élégants blocs de grès rouge, elle témoigne du dialogue et de la concorde spirituelle en terre malienne.",
        "pourquoi_ce_lieu_compte": "Témoin majeur de l'histoire religieuse et de la tolérance séculaire du Mali.",
        "route_path": "/culture/monument/monument_cathedrale_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé",
    },
    {
        "id": "monument_grande_mosquee_bamako",
        "nom": "Grande Mosquée de Bamako",
        "sous_titre": "Le Phare Spirituel au Cœur du Bozola",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Édifiée en 1948 • Reconstruite dans les années 1970",
        "style_architectural": "Mosquée moderne à minarets multiples et coupoles en marbre et faïence",
        "details_localisation": "Quartier Bozola, près du Grand Marché Rose, Commune II",
        "photo_url": "assets/images/culture/monuments/mosquee_djingareyber.jpg",
        "tag": "Sanctuaire Religieux Majeur",
        "latitude": 12.6489,
        "longitude": -7.9925,
        "badge_debloque": "Fidèle du Bozola",
        "xp_recompense": 50,
        "mots_cles": ["mosquee", "grande mosquee", "bamako", "bozola", "marche", "minaret", "priere"],
        "caracteristiques_detection": [
            {"label": "Minarets jumelés blancs culminant au centre-ville", "confidence": 0.991, "category": "Structure", "icon": "mosque_rounded"},
            {"label": "Coupoles et arcades de style islamique saharien", "confidence": 0.984, "category": "Architecture", "icon": "account_balance_rounded"},
            {"label": "Cour intérieure pavée de marbre", "confidence": 0.976, "category": "Matériau", "icon": "grid_on_rounded"},
        ],
        "secrets_et_mysteres": "La mosquée a été construite sur l'emplacement originel du village fondateur des pêcheurs Bozo, premiers habitants des rives de Bamako.",
        "recit_historique": "Point de ralliement des grandes prières du vendredi et des fêtes de l'Aïd, elle est le principal édifice musulman de la capitale.",
        "narration_audio_texte": "La Grande Mosquée de Bamako dresse ses minarets au cœur du quartier historique de Bozola. Elle symbolise la foi profonde et le rayonnement de la culture islamique malienne.",
        "pourquoi_ce_lieu_compte": "Épicentre de la vie religieuse et communautaire de Bamako.",
        "route_path": "/culture/monument/monument_grande_mosquee_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé",
    },

    # ── B. MONUMENTS HISTORIQUES DES AUTRES RÉGIONS DU MALI ───────────────────
    {
        "id": "monument_mosquee_djenne",
        "nom": "Grande Mosquée de Djenné",
        "sous_titre": "Le plus grand édifice en terre crue au monde",
        "region_id": "mopti",
        "region_nom": "Mopti",
        "ville": "Djenné",
        "epoque": "Érigée en 1907 (fondations originelles du XIIIe siècle)",
        "style_architectural": "Style soudano-sahélien en banco, poutres de rônier (torons), minarets crénelés",
        "details_localisation": "Bord du fleuve Bani, Cité millénaire de Djenné",
        "photo_url": "assets/images/culture/monuments/mosquee_djenne.jpg",
        "tag": "Patrimoine Mondial UNESCO",
        "latitude": 13.9056,
        "longitude": -4.5558,
        "badge_debloque": "Gardien du Banco Millénaire",
        "xp_recompense": 70,
        "mots_cles": ["djenne", "mosquee", "banco", "terre", "mopti", "toron", "unesco", "bani", "crepissage"],
        "caracteristiques_detection": [
            {"label": "Texture Banco & Argile alluviale crue", "confidence": 0.992, "category": "Matériau", "icon": "grain_rounded"},
            {"label": "Poutres de rônier apparentes (Torons)", "confidence": 0.985, "category": "Structure", "icon": "architecture_rounded"},
            {"label": "Minarets crénelés avec œufs d'autruche sacrés", "confidence": 0.978, "category": "Symbole", "icon": "brightness_high_rounded"},
            {"label": "Contreforts coniques soudanais", "confidence": 0.969, "category": "Géométrie", "icon": "view_in_ar_rounded"},
        ],
        "secrets_et_mysteres": "Chaque année, lors de la fête du Crépissage (Béré-Goun), plus de 4 000 habitants restaurent l'intégralité des façades en une seule journée festive.",
        "recit_historique": "Édifiée pour la première fois au XIIIe siècle par le roi Koy Koumboro converti à l'islam, la Grande Mosquée de Djenné est le couronnement absolu du génie architectural sahélien.",
        "narration_audio_texte": "Vous observez la majestueuse Grande Mosquée de Djenné, classée au patrimoine mondial de l'UNESCO. Cet édifice est le plus grand monument en terre crue de notre planète.",
        "pourquoi_ce_lieu_compte": "Elle incarne la maîtrise ancestrale des matériaux écologiques locaux et le triomphe de la solidarité communautaire malienne.",
        "route_path": "/culture/monument/monument_mosquee_djenne",
        "modele_3d_url": "assets/models/mosquee_djenne.glb",
        "ar_disponible": True,
        "statut_validation": "Patrimoine Mondial UNESCO",
    },
    {
        "id": "monument_tata_sikasso",
        "nom": "Le Tata de Sikasso",
        "sous_titre": "La Muraille de Résistance du Kénédougou",
        "region_id": "sikasso",
        "region_nom": "Sikasso",
        "ville": "Sikasso",
        "epoque": "Édifié entre 1877 et 1890 par le roi Tiéba Traoré",
        "style_architectural": "Fortification militaire massive en banco durci et blocs de latérite",
        "details_localisation": "Colline du Mamelon, Centre de Sikasso",
        "photo_url": "assets/images/culture/monuments/tata_sikasso.jpg",
        "tag": "Monument National de Résistance",
        "latitude": 11.3176,
        "longitude": -5.6665,
        "badge_debloque": "Bravoure du Kénédougou",
        "xp_recompense": 65,
        "mots_cles": ["sikasso", "tata", "rempart", "muraille", "tieba", "babemba", "traore", "kenedougou", "mamelon"],
        "caracteristiques_detection": [
            {"label": "Blocs de latérite taillée & terre rouge cuite", "confidence": 0.988, "category": "Matériau", "icon": "layers_rounded"},
            {"label": "Épaisseur défensive (3 à 6 mètres)", "confidence": 0.974, "category": "Structure", "icon": "shield_rounded"},
            {"label": "Meurtrières de tir & créneaux de garde", "confidence": 0.965, "category": "Tactique", "icon": "security_rounded"},
        ],
        "secrets_et_mysteres": "Le Tata mesurait à son apogée plus de 9 kilomètres de circonférence. En 1898, encerclé par les troupes coloniales, le roi Babemba Traoré s'exclama : 'Plutôt la mort que la honte' (Sayi té Maloya Sa).",
        "recit_historique": "Chef-d'œuvre de génie militaire précolonial ouest-africain, le Tata de Sikasso est l'ultime forteresse de la dignité souveraine.",
        "narration_audio_texte": "Voici les vestiges héroïques du Tata de Sikasso, l'enceinte fortifiée du royaume du Kénédougou. Érigée par Tiéba Traoré et défendue jusqu'au dernier souffle par son frère Babemba en 1898.",
        "pourquoi_ce_lieu_compte": "Témoignage suprême du refus de la servitude et du sens aigu de l'indépendance nationale.",
        "route_path": "/culture/monument/monument_tata_sikasso",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Monument National",
    },
    {
        "id": "monument_tombeau_askia",
        "nom": "Tombeau pyramidal des Askia",
        "sous_titre": "Symbole de la gloire impériale Songhoï",
        "region_id": "gao",
        "region_nom": "Gao",
        "ville": "Gao",
        "epoque": "Construit en 1495 par l'empereur Askia Mohammed",
        "style_architectural": "Structure pyramidale à degrés sahélienne avec deux minarets et nécropole sacrée",
        "details_localisation": "Bord du fleuve Niger, Gao",
        "photo_url": "assets/images/culture/monuments/tombeau_askia.jpg",
        "tag": "Patrimoine Mondial UNESCO",
        "latitude": 16.2974,
        "longitude": -0.0447,
        "badge_debloque": "Héritier de l'Empire Songhoï",
        "xp_recompense": 65,
        "mots_cles": ["gao", "askia", "tombeau", "pyramide", "songhoi", "unesco", "mohammed", "sahel"],
        "caracteristiques_detection": [
            {"label": "Forme pyramidale tronquée à degrés (17m)", "confidence": 0.991, "category": "Géométrie", "icon": "change_history_rounded"},
            {"label": "Échafaudages permanents en troncs d'acacia", "confidence": 0.982, "category": "Structure", "icon": "architecture_rounded"},
            {"label": "Enduit d'argile fine du lit du Niger", "confidence": 0.970, "category": "Matériau", "icon": "brush_rounded"},
        ],
        "secrets_et_mysteres": "Askia Mohammed ramena de la terre et de l'eau bénite de La Mecque en 1496 pour sceller les fondations spirituelles de ce tombeau impérial.",
        "recit_historique": "Témoin de la puissance commerciale, intellectuelle et militaire de l'Empire Songhoï aux XVe et XVIe siècles, le tombeau est l'unique complexe pyramidal en banco préservé dans tout le Sahara.",
        "narration_audio_texte": "Vous contemplez le Tombeau des Askia à Gao, joyau de l'Empire Songhoï bâti en 1495 par l'empereur Askia Mohammed. Sa forme pyramidale singulière s'élève à 17 mètres de haut au-dessus du fleuve Niger.",
        "pourquoi_ce_lieu_compte": "L'un des plus prestigieux complexes monumentaux de l'Afrique subsaharienne précoloniale.",
        "route_path": "/culture/monument/monument_tombeau_askia",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Patrimoine Mondial UNESCO",
    },
    {
        "id": "monument_djingareyber",
        "nom": "Mosquée Djingareyber",
        "sous_titre": "Sanctuaire d'or et de manuscrits de Tombouctou",
        "region_id": "tombouctou",
        "region_nom": "Tombouctou",
        "ville": "Tombouctou",
        "epoque": "Commandée en 1327 par l'empereur Mansa Moussa",
        "style_architectural": "Style soudano-andalou en banco, piliers intérieurs monumentaux, toiture en troncs de rônier",
        "details_localisation": "Quartier historique, Cité des 333 Saints, Tombouctou",
        "photo_url": "assets/images/culture/monuments/mosquee_djingareyber.jpg",
        "tag": "Patrimoine Mondial UNESCO",
        "latitude": 16.7725,
        "longitude": -3.0076,
        "badge_debloque": "Érudit des Sables de Tombouctou",
        "xp_recompense": 70,
        "mots_cles": ["tombouctou", "djingareyber", "mansa", "moussa", "saheli", "mosquee", "manuscrit", "unesco"],
        "caracteristiques_detection": [
            {"label": "Minaret conique en terre à escalier extérieur", "confidence": 0.987, "category": "Structure", "icon": "stairs_rounded"},
            {"label": "Arcs andalous & piliers de banco massifs", "confidence": 0.979, "category": "Architecture", "icon": "domain_rounded"},
            {"label": "Calcaire de banco et terre crue séchée", "confidence": 0.971, "category": "Matériau", "icon": "grain_rounded"},
        ],
        "secrets_et_mysteres": "Mansa Moussa offrit 200 kilogrammes d'or pur à l'architecte andalou Abou Ishaq es-Sahéli pour concevoir cette merveille en 1327.",
        "recit_historique": "Djingareyber est la plus ancienne mosquée préservée de Tombouctou, au cœur du rayonnement intellectuel universel de la Cité des 333 Saints.",
        "narration_audio_texte": "Voici Djingareyber, la plus ancienne mosquée de Tombouctou, érigée en 1327 sur ordre de Mansa Moussa. Conçue par l'architecte andalou Abou Ishaq es-Sahéli.",
        "pourquoi_ce_lieu_compte": "Le phare historique de l'âge d'or intellectuel et de la tolérance humaniste africaine.",
        "route_path": "/culture/monument/monument_djingareyber",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Patrimoine Mondial UNESCO",
    },
    {
        "id": "monument_sankore",
        "nom": "Mosquée et Université de Sankoré",
        "sous_titre": "Le Berceau du Savoir Universel et des Manuscrits",
        "region_id": "tombouctou",
        "region_nom": "Tombouctou",
        "ville": "Tombouctou",
        "epoque": "Fondée vers 1300, réaménagée sous Askia Mohammed en 1578",
        "style_architectural": "Architecture en banco soudanais avec cour sacrée respectant les dimensions de la Kaaba",
        "details_localisation": "Nord de Tombouctou, Quartier Sankoré",
        "photo_url": "assets/images/culture/monuments/mosquee_sankore.jpg",
        "tag": "Patrimoine Mondial UNESCO",
        "latitude": 16.7778,
        "longitude": -3.0033,
        "badge_debloque": "Maître des Sciences de Sankoré",
        "xp_recompense": 70,
        "mots_cles": ["sankore", "universite", "tombouctou", "ahmed", "baba", "manuscrits", "savoir", "unesco"],
        "caracteristiques_detection": [
            {"label": "Minaret pyramidale à renforts en bois de rônier", "confidence": 0.985, "category": "Structure", "icon": "castle_rounded"},
            {"label": "Cour intérieure aux proportions sacrées", "confidence": 0.976, "category": "Géométrie", "icon": "square_foot_rounded"},
            {"label": "Bibliothèque des manuscrits anciens en ajami", "confidence": 0.989, "category": "Patrimoine", "icon": "auto_stories_rounded"},
        ],
        "secrets_et_mysteres": "L'illustre savant Ahmed Baba (1556-1627) y enseignait et possédait une bibliothèque personnelle de plus de 1 600 ouvrages rares.",
        "recit_historique": "L'Université de Sankoré accueillait plus de 25 000 étudiants au XVIe siècle, étudiant l'astronomie, l'algèbre et la chirurgie.",
        "narration_audio_texte": "Vous regardez l'Université et Mosquée de Sankoré. C'est ici que l'érudit Ahmed Baba a démontré au monde entier la grandeur de la pensée scientifique africaine.",
        "pourquoi_ce_lieu_compte": "Prouve la place centrale du Mali dans l'histoire de la science mondiale et de la culture écrite.",
        "route_path": "/culture/monument/monument_sankore",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Patrimoine Mondial UNESCO",
    },
    {
        "id": "monument_fort_medine",
        "nom": "Fort de Médine",
        "sous_titre": "Sentinelle historique de pierre sur le Haut-Sénégal",
        "region_id": "kayes",
        "region_nom": "Kayes",
        "ville": "Kayes",
        "epoque": "Construit en 1855 sous le règne du roi du Khasso Hawa Demba Diallo",
        "style_architectural": "Fortification militaire en pierres taillées de grès rouge et mortier de chaux",
        "details_localisation": "Bord du fleuve Sénégal, à 12 km de Kayes",
        "photo_url": "assets/images/culture/monuments/fort_medine.jpg",
        "tag": "Monument Historique National",
        "latitude": 14.3756,
        "longitude": -11.3653,
        "badge_debloque": "Vigie du Khasso",
        "xp_recompense": 55,
        "mots_cles": ["kayes", "medine", "fort", "khasso", "senegal", "elhadj", "tall", "pierre"],
        "caracteristiques_detection": [
            {"label": "Appareillage en pierres rouges de latérite taillée", "confidence": 0.984, "category": "Matériau", "icon": "handyman_rounded"},
            {"label": "Tour de guet cylindrique & bastions d'artillerie", "confidence": 0.978, "category": "Structure", "icon": "visibility_rounded"},
            {"label": "Remparts surplombant le cours du fleuve Sénégal", "confidence": 0.968, "category": "Topographie", "icon": "water_rounded"},
        ],
        "secrets_et_mysteres": "Le fort fut le théâtre du célèbre siège de 97 jours en 1857 mené par l'Almamy El Hadj Oumar Tall.",
        "recit_historique": "Bâti pour contrôler la navigation fluviale sur le Haut-Sénégal, Médine est un carrefour capital de l'histoire militaire du XIXe siècle.",
        "narration_audio_texte": "Voici le Fort de Médine, dressé au bord du fleuve Sénégal près de Kayes. Construit en 1855 en solides pierres taillées de grès.",
        "pourquoi_ce_lieu_compte": "Témoin clé de l'épopée toucouleure et de l'histoire fluviale du Mali.",
        "route_path": "/culture/monument/monument_fort_medine",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Monument National",
    },
    {
        "id": "monument_kamablon_kangaba",
        "nom": "Sanctuaire Sacré Kamablon de Kangaba",
        "sous_titre": "Le Cœur Sacré de la Charte de Kouroukan Fouga",
        "region_id": "koulikoro",
        "region_nom": "Koulikoro",
        "ville": "Kangaba",
        "epoque": "Fondé au XIIIe siècle par Mansa Soundiata Keïta (1236)",
        "style_architectural": "Case ronde sacrée en terre crue recouverte d'un toit conique de chaume tressé",
        "details_localisation": "Place sacrée de Kangaba, Cœur historique du Manden",
        "photo_url": "assets/images/culture/personnages/soundiata.jpg",
        "tag": "Patrimoine Immatériel UNESCO",
        "latitude": 11.9333,
        "longitude": -8.4167,
        "badge_debloque": "Initié de Kouroukan Fouga",
        "xp_recompense": 65,
        "mots_cles": ["kamablon", "kangaba", "soundiata", "kouroukan", "fouga", "charte", "manden", "toit"],
        "caracteristiques_detection": [
            {"label": "Case circulaire sacrée en banco poli", "confidence": 0.990, "category": "Structure", "icon": "circle_rounded"},
            {"label": "Toit de chaume conique rituel renouvelé tous les 7 ans", "confidence": 0.985, "category": "Tradition", "icon": "roofing_rounded"},
        ],
        "secrets_et_mysteres": "Tous les sept ans, les griots Diabaté de Kéla et les Keïta s'unissent pour la cérémonie solennelle de réfection du toit et la récitation intégrale de l'épopée mandingue.",
        "recit_historique": "C'est dans cette région que fut proclamée la Charte de Kouroukan Fouga en 1236, proclamant l'égalité des vies et les droits fondamentaux.",
        "narration_audio_texte": "Le sanctuaire du Kamablon à Kangaba est le temple de la mémoire mandingue. Ici a retenti la Charte de 1236, pionnière mondiale des droits de l'homme.",
        "pourquoi_ce_lieu_compte": "Berceau originel de la constitution morale et sociale du Mali.",
        "route_path": "/culture/personnage/perso_soundiata",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Patrimoine Mondial UNESCO",
    },
    {
        "id": "monument_sogolon_bamako",
        "nom": "Statue de Sogolon Kolonkan",
        "sous_titre": "Hommage à la Mère Légendaire et Reine du Mandé",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Époque contemporaine • Hommage au XIIIe siècle",
        "style_architectural": "Statue monumentale en bronze figurant l'héroïne mandingue",
        "details_localisation": "Hamdallaye ACI 2000, Bamako",
        "photo_url": "assets/images/culture/monuments/monument_sogolon_bamako/sog1.jpg",
        "tag": "Matrimoine & Mémoire Mandingue",
        "latitude": 12.6340,
        "longitude": -8.0200,
        "badge_debloque": "Guerrière du Manden",
        "xp_recompense": 50,
        "mots_cles": ["sogolon", "kolonkan", "soundiata", "mande", "mere", "femme", "aci 2000", "bamako"],
        "caracteristiques_detection": [
            {"label": "Sculpture féminine héroïque en bronze", "confidence": 0.992, "category": "Statue", "icon": "woman_rounded"},
            {"label": "Parures traditionnelles mandingues sculptées", "confidence": 0.985, "category": "Détail", "icon": "auto_awesome_rounded"},
        ],
        "secrets_et_mysteres": "Sogolon Kolonkan est réputée dans l'épopée pour sa clairvoyance et ses pouvoirs spirituels qui permirent à Soundiata de déjouer les pièges de Soumaoro Kanté.",
        "recit_historique": "Figure majeure de l'épopée mandingue, sœur et protectrice de l'empereur Soundiata Keïta, symbole du rôle central des femmes dans la fondation de l'Empire du Mali.",
        "narration_audio_texte": "La statue de Sogolon Kolonkan célèbre la bravoure et la sagesse des femmes fondatrices du Mali. Elle incarne la dignité et la protection des lignées ancestrales.",
        "pourquoi_ce_lieu_compte": "Célébration du rôle héroïque et spirituel des femmes dans l'histoire mandingue.",
        "route_path": "/culture/monument/monument_sogolon_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Patrimoine National Validé",
    },
    {
        "id": "monument_al_quouds",
        "nom": "Monument Al-Qoods",
        "sous_titre": "Symbole de Solidarité et de Fraternité Internationale",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Fin du XXe siècle",
        "style_architectural": "Rotonde à colonnades surmontée d'un dôme doré",
        "details_localisation": "Rond-point Al-Qods, Hamdallaye ACI 2000",
        "photo_url": "assets/images/culture/monuments/monument_al_quouds/ref_Q1.jpg",
        "tag": "Solidarité Internationale",
        "latitude": 12.6360,
        "longitude": -8.0250,
        "badge_debloque": "Messager de Fraternité",
        "xp_recompense": 50,
        "mots_cles": ["al quouds", "al qods", "dome", "dore", "aci 2000", "hamdallaye", "bamako"],
        "caracteristiques_detection": [
            {"label": "Coupole hémisphérique dorée", "confidence": 0.990, "category": "Structure", "icon": "mosque_rounded"},
            {"label": "Piliers et arcades orientales", "confidence": 0.980, "category": "Architecture", "icon": "account_balance_rounded"},
        ],
        "secrets_et_mysteres": "Inauguré pour témoigner de la fraternité séculaire du peuple malien avec les causes de paix dans le monde.",
        "recit_historique": "Érigé au cœur du quartier d'affaires d'Hamdallaye ACI 2000, le monument est un repère urbain emblématique des grandes avenues de Bamako.",
        "narration_audio_texte": "Le Monument Al-Qoods brille de son dôme doré sous le soleil de Bamako, marquant l'ouverture du Mali sur le dialogue et la paix entre les peuples.",
        "pourquoi_ce_lieu_compte": "Repère architectural majeur et symbole d'amitié internationale.",
        "route_path": "/culture/monument/monument_al_quouds",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Patrimoine National Validé",
    },
    {
        "id": "monument_maliba_bamako",
        "nom": "Monument MaliBa",
        "sous_titre": "Emblème de la Fierté Nationale et du Renouveau Républicain",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "XXIe siècle",
        "style_architectural": "Typographie monumentale sculptée aux couleurs nationales",
        "details_localisation": "Avenue de la Nation, Bamako",
        "photo_url": "assets/images/culture/monuments/monument_maliba_bamako/mali_1.jpg",
        "tag": "Fierté Patriotique",
        "latitude": 12.6480,
        "longitude": -8.0010,
        "badge_debloque": "Fils du Grand Mali",
        "xp_recompense": 50,
        "mots_cles": ["maliba", "mali ba", "lettres", "vert jaune rouge", "drapeau", "bamako"],
        "caracteristiques_detection": [
            {"label": "Grandes lettres en relief formant MALIBA", "confidence": 0.995, "category": "Structure", "icon": "flag_rounded"},
            {"label": "Tricolore Vert Jaune Rouge", "confidence": 0.985, "category": "Couleur", "icon": "palette_rounded"},
        ],
        "secrets_et_mysteres": "MaliBa signifie 'Le Grand Mali' en langue bamanan, rappelant l'héritage impérial et l'aspiration à la grandeur collective.",
        "recit_historique": "Point de ralliement populaire des jeunes et des visiteurs, ce monument célèbre l'unité républicaine et l'amour de la patrie.",
        "narration_audio_texte": "MaliBa ! En ces lettres grandioses vibre toute l'âme d'un peuple fier de son passé et résolu à bâtir un avenir radieux.",
        "pourquoi_ce_lieu_compte": "Lieu de communion civique et de patriotisme rayonnant.",
        "route_path": "/culture/monument/monument_maliba_bamako",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Patrimoine National Validé",
    },
    {
        "id": "monument_obelisque_bamako",
        "nom": "Obélisque de Bamako",
        "sous_titre": "Le Repère Civique et Historique de la Capitale",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "Début du XXe siècle",
        "style_architectural": "Obélisque monumental en pierre taillée sur piédestal cérémoniel",
        "details_localisation": "Place de la Liberté, Centre-ville, Commune III, Bamako",
        "photo_url": "assets/images/culture/monuments/monument_obelisque_bamako/ob10.jpg",
        "tag": "Cœur Civique & Historique",
        "latitude": 12.6510,
        "longitude": -7.9985,
        "badge_debloque": "Citoyen de la Liberté",
        "xp_recompense": 50,
        "mots_cles": ["obelisque", "liberte", "place", "centre-ville", "bamako", "commune 3"],
        "caracteristiques_detection": [
            {"label": "Obélisque vertical en pierre", "confidence": 0.990, "category": "Structure", "icon": "account_balance_rounded"},
            {"label": "Piédestal carré pavé", "confidence": 0.980, "category": "Architecture", "icon": "layers_rounded"},
        ],
        "secrets_et_mysteres": "Point zéro historique marquant l'axe de développement urbain moderne de Bamako.",
        "recit_historique": "Carrefour historique entre la cité marchande et le plateau administratif de Koulouba.",
        "narration_audio_texte": "Vous voici devant l'Obélisque de Bamako, élevé au cœur de la Place de la Liberté.",
        "pourquoi_ce_lieu_compte": "Symbole central de l'histoire urbaine de Bamako.",
        "route_path": "/culture/monuments",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé",
    },
    {
        "id": "monument_Place_de_la_liberté",
        "nom": "Place de la Liberté",
        "sous_titre": "L'Esplanade Historique de la République",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "ville": "Bamako",
        "epoque": "XXe siècle",
        "style_architectural": "Esplanade urbaine circulaire avec allées d'arbres centenaires",
        "details_localisation": "Centre-ville, Commune III, Bamako",
        "photo_url": "assets/images/culture/monuments/monument_Place_de_la_liberté/lib1.jpg",
        "tag": "Cœur Urbain & Citoyen",
        "latitude": 12.6514,
        "longitude": -7.9982,
        "badge_debloque": "Pèlerin de la Liberté",
        "xp_recompense": 50,
        "mots_cles": ["place", "liberte", "esplanade", "bamako", "centre-ville"],
        "caracteristiques_detection": [
            {"label": "Esplanade circulaire arborée", "confidence": 0.988, "category": "Urbanisme", "icon": "nature_people_rounded"},
            {"label": "Perspectives coloniales et modernes", "confidence": 0.980, "category": "Vue", "icon": "visibility_rounded"},
        ],
        "secrets_et_mysteres": "Espace de rassemblement civique témoin des grands rendez-vous républicains.",
        "recit_historique": "La Place de la Liberté est le centre névralgique de la ville depuis plus d'un siècle.",
        "narration_audio_texte": "Bienvenue sur la Place de la Liberté, véritable carrefour de vie et d'histoire de Bamako.",
        "pourquoi_ce_lieu_compte": "Cœur battant de la capitale malienne.",
        "route_path": "/culture/monuments",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Validé",
    },
    {
        "id": "segou",
        "nom": "Ségou-Koro (Cité des Balanzans)",
        "sous_titre": "Berceau de Biton Coulibaly et du Royaume Bamanan",
        "region_id": "segou",
        "region_nom": "Ségou",
        "ville": "Ségou",
        "epoque": "Fondée en 1712 par Biton Mamary Coulibaly",
        "style_architectural": "Architecture soudanaise traditionnelle en banco et pierres sacrées",
        "details_localisation": "Ségou-Koro, rives du fleuve Niger",
        "photo_url": "assets/images/culture/monuments/segou/segou_!.jpg",
        "tag": "Cité Historique Royale",
        "latitude": 13.4333,
        "longitude": -6.2667,
        "badge_debloque": "Tondjon de Ségou",
        "xp_recompense": 60,
        "mots_cles": ["segou", "segou koro", "biton", "coulibaly", "balanzans", "bambara", "royaume", "djoliba"],
        "caracteristiques_detection": [
            {"label": "Tombeaux royaux et vestibules en banco", "confidence": 0.990, "category": "Structure", "icon": "castle_rounded"},
            {"label": "Rives du fleuve Niger et balanzans centenaires", "confidence": 0.982, "category": "Environnement", "icon": "water_rounded"},
        ],
        "secrets_et_mysteres": "Le secret des 4444 balanzans de Ségou : l'un d'eux est dit invisible aux profanes et ne se révèle qu'aux initiés vertueux.",
        "recit_historique": "Ancienne capitale du grand Royaume Bamanan de Ségou, cette cité garde la mémoire des braves Tondjons et de Biton Coulibaly.",
        "narration_audio_texte": "Bienvenue à Ségou-Koro, la cité où les balanzans murmurent encore les exploits des rois guerriers du Mali. Laissez-vous porter par les flots majestueux du Djoliba.",
        "pourquoi_ce_lieu_compte": "Haut lieu de l'épopée royale bambara et de la culture fluviale sahélienne.",
        "route_path": "/culture/monument/segou",
        "modele_3d_url": None,
        "ar_disponible": False,
        "statut_validation": "Patrimoine National Validé",
    },
]


# ==============================================================================
# 2. GRANDS PERSONNAGES HISTORIQUES
# ==============================================================================

PERSONNAGES_DATA = [
    {
        "id": "perso_soundiata",
        "nom": "Soundiata Keïta",
        "titre_honorifique": "Le Lion du Manden & Fondateur de l'Empire du Mali",
        "periode": "1190 – 1255",
        "region_id": "koulikoro",
        "region_nom": "Koulikoro / Manden",
        "tag": "Mansa Bâtisseur",
        "photo_url": "assets/images/culture/personnages/soundiata.jpg",
        "photo_credits": "Mémorial Historique du Manden, Kangaba • Archives Nationales",
        "resume": "Bâtisseur de l'Empire du Mali après sa victoire décisive à Kirina en 1235, il proclame en 1236 la Charte de Kouroukan Fouga, l'une des premières déclarations des droits humains.",
        "citation_historique": "« Toute vie humaine est une vie. Le tort fait à autrui demande réparation. Respectez l'étranger, l'aîné et la femme. » — Charte du Manden, 1236",
        "faits_marquants": [
            {"label": "Règne", "value": "1235 – 1255", "icon": "workspace_premium_rounded"},
            {"label": "Victoire majeure", "value": "Bataille de Kirina (1235)", "icon": "shield_rounded"},
            {"label": "Héritage universel", "value": "Charte du Manden (UNESCO)", "icon": "auto_stories_rounded"},
            {"label": "Capitale originelle", "value": "Niani", "icon": "location_city_rounded"},
        ],
        "chapitres": [
            {"title": "L'Enfance et la Prophétie du Manden", "content": "Fils de Naré Maghann Konaté et de Sogolon Kondé, Soundiata naît paralysé des jambes mais se redresse grâce à sa force d'âme."},
            {"title": "La Victoire de Kirina (1235)", "content": "Il défait le roi Soumaoro Kanté du Sosso et unifie les tribus du fleuve Niger."},
            {"title": "La Charte de Kouroukan Fouga (1236)", "content": "Constitution orale sacralisant la dignité humaine, la paix sociale et la préservation de la nature."},
        ],
        "elements_lies": [
            {"id": "monument_kamablon_kangaba", "title": "Sanctuaire Kamablon", "subtitle": "Cœur de la Charte de 1236", "type": "monument", "tag": "UNESCO", "regionName": "Koulikoro"},
            {"id": "monument_independance_bamako", "title": "Monument Indépendance", "subtitle": "Héritier de la liberté", "type": "monument", "tag": "Bamako", "regionName": "Bamako"},
        ],
    },
    {
        "id": "perso_mansa_moussa",
        "nom": "Mansa Moussa",
        "titre_honorifique": "Le Souverain d'Or & Bâtisseur du Savoir Universel",
        "periode": "1312 – 1337",
        "region_id": "tombouctou",
        "region_nom": "Tombouctou",
        "tag": "Mansa Légendaire",
        "photo_url": "assets/images/culture/personnages/mansa_moussa.jpg",
        "photo_credits": "Atlas Catalan d'Abraham Cresques (1375) • Bibliothèque Nationale",
        "resume": "Dixième Mansa de l'Empire du Mali, célèbre pour son pèlerinage fastueux de 1324 et pour avoir fait de Tombouctou la capitale intellectuelle de l'Afrique avec la mosquée Djingareyber.",
        "citation_historique": "« L'or n'a de véritable valeur que lorsqu'il sert à éclairer les esprits et à édifier les demeures du savoir. »",
        "faits_marquants": [
            {"label": "Pèlerinage historique", "value": "1324 à La Mecque", "icon": "explore_rounded"},
            {"label": "Fondation majeure", "value": "Mosquée Djingareyber (1327)", "icon": "account_balance_rounded"},
            {"label": "Rayonnement mondial", "value": "Atlas Catalan de 1375", "icon": "public_rounded"},
        ],
        "chapitres": [
            {"title": "L'Ascension du Souverain de l'Or", "content": "Sous son règne, le Mali contrôlait plus de la moitié de l'or circulant dans le monde méditerranéen."},
            {"title": "Le Voyage qui changea la vision du monde", "content": "Son passage au Caire en 1324 marqua l'histoire économique par la générosité de ses aumônes."},
            {"title": "L'Âge d'Or de Tombouctou", "content": "Il invita poètes, érudits et architectes pour transformer Tombouctou en métropole universitaire."},
        ],
        "elements_lies": [
            {"id": "monument_djingareyber", "title": "Mosquée Djingareyber", "subtitle": "Bâtie en 1327", "type": "monument", "tag": "UNESCO", "regionName": "Tombouctou"},
            {"id": "monument_sankore", "title": "Université de Sankoré", "subtitle": "Savoir Universel", "type": "monument", "tag": "UNESCO", "regionName": "Tombouctou"},
        ],
    },
    {
        "id": "perso_askia_mohammed",
        "nom": "Askia Mohammed Touré",
        "titre_honorifique": "Le Grand Réformateur de l'Empire Songhoï",
        "periode": "1443 – 1538",
        "region_id": "gao",
        "region_nom": "Gao",
        "tag": "Empereur Réformateur",
        "photo_url": "assets/images/culture/personnages/askia_mohammed.jpg",
        "photo_credits": "Chroniques du Tarikh el-Fettach • Archives de Gao",
        "resume": "Fondateur de la dynastie des Askia en 1493, il réorganisa l'administration impériale, soutint l'essor de la science et érigea le complexe pyramidal de Gao.",
        "citation_historique": "« Un empire ne se maintient point par l'épée seule, mais par la justice des juges et la clarté des lois. »",
        "faits_marquants": [
            {"label": "Règne", "value": "1493 – 1528", "icon": "workspace_premium_rounded"},
            {"label": "Monuments", "value": "Tombeau des Askia (1495)", "icon": "museum_rounded"},
        ],
        "chapitres": [
            {"title": "La Prise de Pouvoir et les Réformes", "content": "Askia Mohammed unifia le Songhoï en instaurant des gouverneurs de province efficaces."},
        ],
        "elements_lies": [
            {"id": "monument_tombeau_askia", "title": "Tombeau des Askia", "subtitle": "Nécropole pyramidale", "type": "monument", "tag": "UNESCO", "regionName": "Gao"},
        ],
    },
    {
        "id": "perso_babemba_traore",
        "nom": "Babemba Traoré",
        "titre_honorifique": "Le Roi Héroïque du Kénédougou & Héros de Sikasso",
        "periode": "1855 – 1898",
        "region_id": "sikasso",
        "region_nom": "Sikasso",
        "tag": "Héros de la Résistance",
        "photo_url": "assets/images/culture/personnages/babemba.jpg",
        "photo_credits": "Mémorial du Mamelon, Sikasso",
        "resume": "Dernier roi souverain du Kénédougou, il a défendu Sikasso face aux assauts coloniaux et s'est donné la mort en 1898 selon la devise 'Sayi té Maloya Sa' (Plutôt la mort que la honte).",
        "citation_historique": "« Sayi té Maloya Sa ! La terre de nos aïeux ne verra pas ma soumission vivant. »",
        "faits_marquants": [
            {"label": "Résistance", "value": "Siège de Sikasso (1898)", "icon": "shield_rounded"},
        ],
        "chapitres": [
            {"title": "La Défense Inébranlable du Kénédougou", "content": "À la tête du Tata fortifié de Sikasso, il préféra la dignité suprême à la reddition."},
        ],
        "elements_lies": [
            {"id": "monument_tata_sikasso", "title": "Le Tata de Sikasso", "subtitle": "Forteresse de banco", "type": "monument", "tag": "Sikasso", "regionName": "Sikasso"},
        ],
    },
    {
        "id": "perso_modibo_keita",
        "nom": "Modibo Keïta",
        "titre_honorifique": "Père de l'Indépendance et Premier Président du Mali",
        "periode": "1915 – 1977",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "tag": "Père de la Nation",
        "photo_url": "assets/images/culture/personnages/soundiata.jpg",
        "photo_credits": "Mémorial Modibo Keïta, Bamako",
        "resume": "Instituteur de formation et militant anticolonialiste d'une intégrité exemplaire, il proclama l'indépendance de la République du Mali le 22 septembre 1960 et fut l'un des pères fondateurs de l'OUA.",
        "citation_historique": "« Lorsque les peuples d'Afrique s'unissent dans la justice, aucune puissance sur terre ne saurait les ramener aux fers. »",
        "faits_marquants": [
            {"label": "Présidence", "value": "1960 – 1968", "icon": "flag_rounded"},
            {"label": "Panafricanisme", "value": "Cofondateur de l'OUA (1963)", "icon": "public_rounded"},
        ],
        "chapitres": [
            {"title": "Le Combat pour la Dignité", "content": "Élu député à l'Assemblée française, il porta sans relâche la voix de l'Afrique souveraine."},
            {"title": "La Proclamation du 22 Septembre 1960", "content": "À Bamako, il proclama la naissance de la République du Mali, résolument souveraine."},
        ],
        "elements_lies": [
            {"id": "monument_independance_bamako", "title": "Monument Indépendance", "subtitle": "Héritage patriotique", "type": "monument", "tag": "Bamako", "regionName": "Bamako"},
            {"id": "monument_tour_afrique_bamako", "title": "Tour de l'Afrique", "subtitle": "Idéal Panafricain", "type": "monument", "tag": "Bamako", "regionName": "Bamako"},
        ],
    },
]


# ==============================================================================
# 3. VILLES ET TERROIRS REMARQUABLES
# ==============================================================================

LIEUX_DATA = [
    {
        "id": "ville_bamako",
        "nom": "Bamako",
        "sous_titre": "La Cité des Trois Caïmans & Cœur Battant du Djoliba",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "tag": "Capitale Nationale",
        "photo_url": "assets/images/culture/villes/djenne_ville.jpg",
        "photo_credits": "Archives Photographiques de Bamako",
        "fondation": "Fondée au XVIe siècle par les Niaré",
        "latitude": 12.6392,
        "longitude": -8.0029,
        "population_ou_details": "~3 000 000 habitants",
        "resume": "Bordée par le fleuve Niger et dominée par les falaises du Point G et de Koulouba, Bamako est le foyer incandescent de la musique, des arts et de la diplomatie sahélienne.",
        "chapitres": [
            {"title": "Les Origines des Trois Caïmans", "content": "Bamba-Kô signifie 'la mare aux caïmans' en langue bamanan. Les familles fondatrices Niaré, Touré et Dravé établirent les pactes ancestraux avec les esprits du fleuve."},
            {"title": "La Métropole Artistique du XXIe siècle", "content": "Haut lieu de la Biennale de la photographie africaine et des orchestres légendaires (Rail Band, Les Ambassadeurs)."},
        ],
        "elements_lies": [
            {"id": "monument_independance_bamako", "title": "Monument Indépendance", "subtitle": "Axe cérémoniel", "type": "monument", "tag": "Bamako", "regionName": "Bamako"},
            {"id": "monument_tour_afrique_bamako", "title": "Tour de l'Afrique", "subtitle": "Porte de Faladié", "type": "monument", "tag": "Bamako", "regionName": "Bamako"},
            {"id": "monument_musee_national_bamako", "title": "Musée National", "subtitle": "Trésor du Mali", "type": "monument", "tag": "Bamako", "regionName": "Bamako"},
        ],
    },
    {
        "id": "ville_djenne",
        "nom": "Djenné",
        "sous_titre": "La Cité Millénaire du Bani & Joyau de Terre Crue",
        "region_id": "mopti",
        "region_nom": "Mopti",
        "tag": "Cité Classée UNESCO",
        "photo_url": "assets/images/culture/villes/djenne_ville.jpg",
        "photo_credits": "Cliché Patrimoine UNESCO",
        "fondation": "Fondée vers 250 av. J.-C. (site de Djenné-Djeno)",
        "latitude": 13.9056,
        "longitude": -4.5558,
        "population_ou_details": "~35 000 habitants",
        "resume": "Plus ancienne ville connue d'Afrique subsaharienne, carrefour de commerce transsaharien et sanctuaire de l'architecture soudanaise en banco.",
        "chapitres": [
            {"title": "Une Histoire de deux mille ans", "content": "Les fouilles archéologiques attestent d'une métallurgie du fer dès le IIIe siècle avant notre ère."},
        ],
        "elements_lies": [
            {"id": "monument_mosquee_djenne", "title": "Grande Mosquée", "subtitle": "Chef-d'œuvre de banco", "type": "monument", "tag": "UNESCO", "regionName": "Mopti"},
        ],
    },
    {
        "id": "ville_tombouctou",
        "nom": "Tombouctou",
        "sous_titre": "La Cité Mystique des 333 Saints et des Manuscrits",
        "region_id": "tombouctou",
        "region_nom": "Tombouctou",
        "tag": "Patrimoine de l'Humanité",
        "photo_url": "assets/images/culture/villes/tombouctou_ville.jpg",
        "photo_credits": "Institut Ahmed Baba",
        "fondation": "Fondée vers 1100 par les Touaregs Imashagan",
        "latitude": 16.7725,
        "longitude": -3.0076,
        "population_ou_details": "~55 000 habitants",
        "resume": "Au bord du désert et de la boucle du Niger, Tombouctou fut la perle des caravanes de sel et d'or et le plus grand foyer universitaire médiéval d'Afrique.",
        "chapitres": [
            {"title": "Le Mythe de Bouctou", "content": "La tradition orale raconte qu'une femme sage nommée Bouctou gardait le puits d'eau où campaient les nomades."},
        ],
        "elements_lies": [
            {"id": "monument_djingareyber", "title": "Mosquée Djingareyber", "subtitle": "Bâtie en 1327", "type": "monument", "tag": "UNESCO", "regionName": "Tombouctou"},
            {"id": "monument_sankore", "title": "Université de Sankoré", "subtitle": "Savoirs manuscrits", "type": "monument", "tag": "UNESCO", "regionName": "Tombouctou"},
        ],
    },
    {
        "id": "ville_segou_koro",
        "nom": "Ségou-Koro",
        "sous_titre": "La Cité des Balanzans et Berceau du Royaume Bamanan",
        "region_id": "segou",
        "region_nom": "Ségou",
        "tag": "Cité Historique Royale",
        "photo_url": "assets/images/culture/villes/segou_koro.jpg",
        "photo_credits": "Office du Tourisme de Ségou",
        "fondation": "Fondée en 1712 par Biton Mamary Coulibaly",
        "latitude": 13.4333,
        "longitude": -6.2667,
        "population_ou_details": "Ancienne capitale royale",
        "resume": "Établie au bord du Djoliba sous l'ombrage des balanzans sacrés, Ségou-Koro garde la mémoire des dynasties royales et des maîtres pêcheurs Somono.",
        "chapitres": [
            {"title": "L'Épopée des Tondjons", "content": "Biton transforma une confrérie de chasseurs en une armée redoutable qui bâtit l'Empire de Ségou."},
        ],
        "elements_lies": [
            {"id": "ville_bamako", "title": "Bamako", "subtitle": "Capitale soeur du Djoliba", "type": "ville", "tag": "Mali", "regionName": "Bamako"},
        ],
    },
]


# ==============================================================================
# 4. CONTES ET FABLES INTERACTIFS
# ==============================================================================

CONTES_DATA = [
    {
        "id": "conte_lievre_hyene",
        "titre": "Zoumana le Lièvre et Namori l'Hyène",
        "sous_titre": "La ruse de l'esprit face à la force et la gourmandise",
        "origine": "Tradition Orale Mandingue",
        "region_id": "bamako",
        "region_nom": "Tout le Mali",
        "tag": "Fable Mandingue",
        "photo_url": "assets/images/culture/contes/savane_crepuscule_stage.jpg",
        "photo_credits": "Archives Nationales du Mali",
        "resume": "Lors d'une sécheresse dans la savane, les animaux creusent un puits commun. Tandis que Namori l'hyène cherche à s'accaparer les réserves, Zoumana use d'intelligence pour rétablir la justice.",
        "conteur": "Griot Mamadou Kouyaté",
        "duree_audio": "5 min 40",
        "duree_lecture": "3 min 30",
        "morale": "« La force sans réflexion creuse son propre piège ; la sagesse et la mesure triomphent toujours de la cupidité. »",
        "scenes": [
            {"id": "scene_1", "sceneNumber": 1, "title": "La Soif de la Savane", "atmosphere": "Crépuscule chaud", "narrativeText": "Le soleil s'enfonce à l'horizon. L'eau vient à manquer dans le village animal."},
            {"id": "scene_2", "sceneNumber": 2, "title": "L'Épreuve du Puits", "atmosphere": "Nuit étoilée", "narrativeText": "Chaque animal participe, mais l'hyène refuse l'effort tout en réclamant la première gorgée."},
        ],
        "elements_lies": [
            {"id": "perso_soundiata", "title": "Soundiata Keïta", "subtitle": "Justice du Manden", "type": "personnage", "tag": "Mansa", "regionName": "Koulikoro"},
        ],
    },
    {
        "id": "conte_soundiata_forge",
        "titre": "Soundiata et la Barre de Fer du Destin",
        "sous_titre": "La persévérance sacrée qui brise les impossibles",
        "origine": "Épopée du Mandé",
        "region_id": "koulikoro",
        "region_nom": "Koulikoro / Kangaba",
        "tag": "Épopée Initiatique",
        "photo_url": "assets/images/culture/contes/manden_baobab_stage.jpg",
        "photo_credits": "Griots de Kéla",
        "resume": "L'histoire poignante de Soundiata enfant, qui se redresse sur ses jambes à l'aide d'une lourde barre forgée par les maîtres du feu, pour essuyer les larmes de sa mère Sogolon.",
        "conteur": "Balla Fasséké Kouyaté",
        "duree_audio": "7 min 15",
        "duree_lecture": "4 min 20",
        "morale": "« Aucun enfant n'est condamné par le sort lorsque brûle en son cœur la foi et le respect filial. »",
        "scenes": [
            {"id": "scene_1", "sceneNumber": 1, "title": "L'Humiliation sous le Baobab", "atmosphere": "Matinée sous le grand baobab", "narrativeText": "La reine mère moque Sogolon Kondé parce que son fils ne marche pas encore."},
            {"id": "scene_2", "sceneNumber": 2, "title": "La Forge des Nègèsso", "atmosphere": "Flammes vives et martèlements", "narrativeText": "Les forgerons apportent l'arc de fer. Soundiata s'y appuie et se dresse debout."},
        ],
        "elements_lies": [
            {"id": "monument_kamablon_kangaba", "title": "Sanctuaire Kamablon", "subtitle": "Terre de Soundiata", "type": "monument", "tag": "UNESCO", "regionName": "Koulikoro"},
        ],
    },
]


# ==============================================================================
# 5. SAGESSES ET PROVERBES DES TERROIRS MALIENS
# ==============================================================================

PROVERBES_DATA = [
    {
        "id": "prov_humilite",
        "texte": "L'eau chaude n'oublie jamais qu'elle a été froide.",
        "texte_original": "Ji kalan tɛ ɲina a nɛnɛ kɔ.",
        "signification": "Peu importe ton ascension, ta gloire ou ta réussite, n'oublie jamais d'où tu viens et conserve l'humilité du premier jour.",
        "morale": "L'humilité face au destin et aux origines",
        "origine": "Tradition Orale Bamanan (Manden)",
        "theme": "Humilité",
        "region_id": "koulikoro",
        "region_nom": "Koulikoro / Manden",
        "xp_recompense": 45,
        "orateur_nom": "Le Sage du Baobab",
        "orateur_role": "Doyen des Sages",
        "accent_color_hex": "#F1851F",
    },
    {
        "id": "prov_parole_eau",
        "texte": "La parole est comme l'eau : une fois versée à terre, nul ne peut la ramasser.",
        "texte_original": "Kuma ye ji ye, n'a bɔra a tɛ se ka sɔrɔ tuguni.",
        "signification": "La parole donnée engage l'honneur et la dignité humaine. Il convient de peser chaque propos avant de le prononcer.",
        "morale": "La valeur sacrée de la parole donnée",
        "origine": "Parole des Griots du Manden",
        "theme": "Honneur & Sagesse",
        "region_id": "bamako",
        "region_nom": "Bamako / Manden",
        "xp_recompense": 40,
        "orateur_nom": "Babani le Griot",
        "orateur_role": "Maître de la Parole",
        "accent_color_hex": "#E65100",
    },
    {
        "id": "prov_experience_segou",
        "texte": "Ce qu'un vieillard voit assis, un jeune homme debout ne peut l'apercevoir.",
        "texte_original": "Kɔrɔkɛ sigilen fɛn min ye, kamalen lɔnin t'o ye.",
        "signification": "L'expérience, le discernement et la sagesse forgés au fil des épreuves surpassent la simple force physique.",
        "morale": "L'expérience surpasse la force brute",
        "origine": "Royaume Bamanan de Ségou",
        "theme": "Sagesse & Respect",
        "region_id": "segou",
        "region_nom": "Ségou",
        "xp_recompense": 50,
        "orateur_nom": "Doyen des Balanzans",
        "orateur_role": "Garde de la Mémoire",
        "accent_color_hex": "#40BBCC",
    },
    {
        "id": "prov_solidarite",
        "texte": "Une seule main ne peut pas applaudir ; c'est avec deux mains qu'on lave un visage propre.",
        "texte_original": "Bolo kelen tɛ se ka kunkolo dabila.",
        "signification": "La solitude rend impuissant ; seule la solidarité collective et l'entraide bâtissent une communauté prospère.",
        "morale": "La force indestructible de l'entraide communautaire",
        "origine": "Proverbe populaire du fleuve Niger",
        "theme": "Solidarité",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "xp_recompense": 45,
        "orateur_nom": "Ancienne du Marché Rose",
        "orateur_role": "Matriarche",
        "accent_color_hex": "#10B981",
    },
    {
        "id": "prov_patience",
        "texte": "La patience est un arbre dont les racines sont amères, mais dont les fruits sont infiniment doux.",
        "texte_original": "Sabali ye fura ye, a dabɔlen ka gɛlɛn nka a den ye duman ye.",
        "signification": "L'endurance dans l'adversité conduit inévitablement au succès et à la paix du cœur.",
        "morale": "La patience triomphe du temps",
        "origine": "Sagesse sahélienne",
        "theme": "Patience",
        "region_id": "tombouctou",
        "region_nom": "Tombouctou",
        "xp_recompense": 45,
        "orateur_nom": "Érudit de Sankoré",
        "orateur_role": "Maître de Connaissance",
        "accent_color_hex": "#314999",
    },
]


# ==============================================================================
# 6. PACKS CULTURELS HORS LIGNE TÉLÉCHARGEABLES
# ==============================================================================

PACKS_DATA = [
    {
        "id": "pack_bamako_capitale",
        "titre": "Pack Bamako — Capitale & Monuments de Souveraineté",
        "description": "Comprend tous les monuments de Bamako (Indépendance, Tour de l'Afrique, Paix, Héros de l'Armée Noire, Musée National, Palais de la Culture), narrations audio haute définition et modèle 3D interactif.",
        "region_id": "bamako",
        "region_nom": "District de Bamako",
        "taille_mo": 14.8,
        "version": "1.0.0",
        "elements_count": 12,
        "inclus": ["12 monuments complets", "Narrations en Français et Bamanankan", "Repères géospatiaux GPS", "Modèles 3D allégés", "Quizz et anecdotes inédites"],
    },
    {
        "id": "pack_mali_patrimoine_mondial",
        "titre": "Pack Trésors UNESCO du Mali",
        "description": "Les joyaux universels : Grande Mosquée de Djenné, Tombeau des Askia de Gao, Mosquées de Tombouctou (Djingareyber & Sankoré) et Sanctuaire Kamablon de Kangaba.",
        "region_id": "mopti",
        "region_nom": "Tout le Mali (UNESCO)",
        "taille_mo": 22.4,
        "version": "1.0.0",
        "elements_count": 8,
        "inclus": ["Sites UNESCO complets", "Fiches historiques détaillées", "Récits oraux des veillées", "Photos d'archives certifiées"],
    },
    {
        "id": "pack_tombouctou_savoir",
        "titre": "Pack Tombouctou — La Cité des 333 Saints & Manuscrits",
        "description": "Exploration approfondie des bibliothèques de manuscrits, de l'astronomie médiévale africaine et de l'héritage d'Ahmed Baba et Mansa Moussa.",
        "region_id": "tombouctou",
        "region_nom": "Tombouctou",
        "taille_mo": 18.2,
        "version": "1.0.0",
        "elements_count": 6,
        "inclus": ["Mosquées Djingareyber & Sankoré", "Portraits d'érudits", "Extraits de manuscrits ajami", "Parcours de la cité sainte"],
    },
    {
        "id": "pack_sud_resistances",
        "titre": "Pack Sud & Résistances — Sikasso, Kayes & Manden",
        "description": "De la muraille du Tata de Sikasso au Fort de Médine et aux Monts Mandingues de Soundiata Keïta.",
        "region_id": "sikasso",
        "region_nom": "Sikasso / Kayes / Manden",
        "taille_mo": 16.5,
        "version": "1.0.0",
        "elements_count": 8,
        "inclus": ["Tata de Sikasso", "Fort de Médine", "Épopée du Kénédougou", "Contes de la savane"],
    },
]


# ==============================================================================
# FONCTION DE PEUPLEMENT CENTRALE
# ==============================================================================

def seed_culture_data(db: Session, force: bool = False):
    """
    Peuple la base de données alta_db avec tous les monuments (priorité Bamako),
    personnages, lieux, contes, proverbes et packs culturels certifiés.
    """
    try:
        from backend.src.db.sync_culture_database import sync_database
        sync_database(db)
        return
    except Exception as exc:
        logger.error(f"Erreur lors du peuplement CultureLens : {exc}")
        print(f"⚠️ Erreur peuplement CultureLens : {exc}")

        # 1. Insertion des Monuments (Bamako & National)
        for m in MONUMENTS_DATA:
            existing = db.query(CultureMonument).filter(CultureMonument.id == m["id"]).first()
            if not existing:
                db.add(CultureMonument(
                    id=m["id"],
                    nom=m["nom"],
                    sous_titre=m["sous_titre"],
                    region_id=m["region_id"],
                    region_nom=m["region_nom"],
                    ville=m["ville"],
                    epoque=m["epoque"],
                    style_architectural=m["style_architectural"],
                    details_localisation=m["details_localisation"],
                    photo_url=m["photo_url"],
                    tag=m.get("tag", "Monument National"),
                    latitude=m["latitude"],
                    longitude=m["longitude"],
                    badge_debloque=m["badge_debloque"],
                    xp_recompense=m.get("xp_recompense", 50),
                    mots_cles_json=json.dumps(m["mots_cles"], ensure_ascii=False),
                    caracteristiques_detection_json=json.dumps(m["caracteristiques_detection"], ensure_ascii=False),
                    secrets_et_mysteres=m["secrets_et_mysteres"],
                    recit_historique=m["recit_historique"],
                    narration_audio_texte=m["narration_audio_texte"],
                    pourquoi_ce_lieu_compte=m["pourquoi_ce_lieu_compte"],
                    route_path=m["route_path"],
                    modele_3d_url=m.get("modele_3d_url"),
                    ar_disponible=m.get("ar_disponible", False),
                    statut_validation=m.get("statut_validation", "Patrimoine vérifié"),
                    date_mise_a_jour=datetime.utcnow(),
                ))

        # 2. Insertion des Personnages
        for p in PERSONNAGES_DATA:
            existing = db.query(CulturePersonnage).filter(CulturePersonnage.id == p["id"]).first()
            if not existing:
                db.add(CulturePersonnage(
                    id=p["id"],
                    nom=p["nom"],
                    titre_honorifique=p["titre_honorifique"],
                    periode=p["periode"],
                    region_id=p["region_id"],
                    region_nom=p["region_nom"],
                    tag=p.get("tag", "Héros Historique"),
                    photo_url=p["photo_url"],
                    photo_credits=p.get("photo_credits"),
                    resume=p["resume"],
                    citation_historique=p.get("citation_historique"),
                    faits_marquants_json=json.dumps(p["faits_marquants"], ensure_ascii=False),
                    chapitres_json=json.dumps(p["chapitres"], ensure_ascii=False),
                    elements_lies_json=json.dumps(p["elements_lies"], ensure_ascii=False),
                    date_creation=datetime.utcnow(),
                ))

        # 3. Insertion des Villes et Terroirs
        for l in LIEUX_DATA:
            existing = db.query(CultureLieu).filter(CultureLieu.id == l["id"]).first()
            if not existing:
                db.add(CultureLieu(
                    id=l["id"],
                    nom=l["nom"],
                    sous_titre=l["sous_titre"],
                    region_id=l["region_id"],
                    region_nom=l["region_nom"],
                    tag=l.get("tag", "Cité Historique"),
                    photo_url=l["photo_url"],
                    photo_credits=l.get("photo_credits"),
                    fondation=l["fondation"],
                    latitude=l["latitude"],
                    longitude=l["longitude"],
                    population_ou_details=l.get("population_ou_details"),
                    resume=l["resume"],
                    chapitres_json=json.dumps(l["chapitres"], ensure_ascii=False),
                    elements_lies_json=json.dumps(l["elements_lies"], ensure_ascii=False),
                    date_creation=datetime.utcnow(),
                ))

        # 4. Insertion des Contes
        for c in CONTES_DATA:
            existing = db.query(CultureConte).filter(CultureConte.id == c["id"]).first()
            if not existing:
                db.add(CultureConte(
                    id=c["id"],
                    titre=c["titre"],
                    sous_titre=c["sous_titre"],
                    origine=c["origine"],
                    region_id=c.get("region_id"),
                    region_nom=c.get("region_nom", "Tout le Mali"),
                    tag=c.get("tag", "Fable & Conte"),
                    photo_url=c["photo_url"],
                    photo_credits=c.get("photo_credits"),
                    resume=c["resume"],
                    conteur=c.get("conteur", "Griot AlternIA"),
                    duree_audio=c.get("duree_audio", "5 min"),
                    duree_lecture=c.get("duree_lecture", "3 min"),
                    morale=c["morale"],
                    scenes_json=json.dumps(c["scenes"], ensure_ascii=False),
                    elements_lies_json=json.dumps(c["elements_lies"], ensure_ascii=False),
                    date_creation=datetime.utcnow(),
                ))

        # 5. Insertion des Proverbes
        for pr in PROVERBES_DATA:
            existing = db.query(CultureProverbe).filter(CultureProverbe.id == pr["id"]).first()
            if not existing:
                db.add(CultureProverbe(
                    id=pr["id"],
                    texte=pr["texte"],
                    texte_original=pr.get("texte_original"),
                    signification=pr["signification"],
                    morale=pr["morale"],
                    origine=pr["origine"],
                    theme=pr["theme"],
                    region_id=pr["region_id"],
                    region_nom=pr["region_nom"],
                    xp_recompense=pr.get("xp_recompense", 40),
                    orateur_nom=pr.get("orateur_nom"),
                    orateur_role=pr.get("orateur_role"),
                    accent_color_hex=pr.get("accent_color_hex", "#F1851F"),
                ))

        # 6. Insertion des Packs hors ligne
        for pk in PACKS_DATA:
            existing = db.query(CulturePack).filter(CulturePack.id == pk["id"]).first()
            if not existing:
                db.add(CulturePack(
                    id=pk["id"],
                    titre=pk["titre"],
                    description=pk["description"],
                    region_id=pk["region_id"],
                    region_nom=pk["region_nom"],
                    taille_mo=pk["taille_mo"],
                    version=pk["version"],
                    elements_count=pk["elements_count"],
                    inclus_json=json.dumps(pk["inclus"], ensure_ascii=False),
                    bundle_data_json=None,
                    date_mise_a_jour=datetime.utcnow(),
                ))

        db.commit()
        print(f"✅ CultureLens peuplé avec succès : {len(MONUMENTS_DATA)} monuments enregistrés (dont {len([m for m in MONUMENTS_DATA if m['ville'] == 'Bamako'])} à Bamako), {len(PERSONNAGES_DATA)} personnages, {len(LIEUX_DATA)} terroirs, {len(CONTES_DATA)} contes, {len(PROVERBES_DATA)} proverbes et {len(PACKS_DATA)} packs.")

    except Exception as exc:
        db.rollback()
        logger.error(f"Erreur lors du peuplement CultureLens : {exc}")
        print(f"⚠️ Erreur peuplement CultureLens : {exc}")
